#!/bin/bash

######################################################
# Folder setting
BASEPATH=$(dirname $PWD)
EXPATH=$(basename $PWD)

DATA_PATH=~/datasets/cvwc/
DATA_PATH_BASE_TRAIN=~/datasets/cvwc/atrw_reid_train/train
DATA_PATH_BASE_TEST=~/datasets/cvwc/atrw_reid_test/test

#######################################################
## Options
SAVE=${EXPATH}/save
SAVE_PATH=${SAVE}/ebay_train
CHECKPOINT=${SAVE}/checkpoint
EVAL_TRAIN=${EXPATH}/evalc_train.dmp
EVAL_TEST=${EXPATH}/evalc_test.dmp
BBOX_PATH=${EXPATH}/bbox.json
DATA_TRAIN=${DATA_PATH}/metric_train.txt
DATA_VAL=${DATA_PATH}/metric_val_short.txt
DATA_TEST=${DATA_PATH}/metric_test.txt
EMB_OPT=" --n_heads=9 --pooling=avgnmax "
TRAIN_OPT="-s ${SAVE_PATH} -b 80 -l 0.0005 --beta1=0.95 --lr_decay_rate=0.5 --sample_normalization --lr_decay_staircase --lr_decay_steps=10000 --positive_probability=0.5 --weight_decay=0.00004 --flat_hardratio=0.5 --weighted_class_sampling -t 1000"${EMB_OPT}
# must be either TRAIN or VAL
PHASE="WILDEVAL"
LOG_FILE=$PWD/$PHASE'.log'
> $LOG_FILE
LAST_STEP=20000

######################################################
# Initialization
cd $BASEPATH

if [ "$PHASE" = "TRAIN" ]; then
	if ! [ -e ${SAVE} ]; then
	    mkdir -p ${SAVE}
	    if [ $? -ne 0 ]; then
	        echo Failed to create ${SAVE}
	        exit
	    fi
	fi

	if ! [ -e ${CHECKPOINT} ] ; then
	    python -u train_hdc_k_all.py -i -d "${DATA_TRAIN}" --data_path_base "${DATA_PATH_BASE_TRAIN}" ${TRAIN_OPT} 2>&1 | tee -a $LOG_FILE
	    sleep 10 # wait for the disk sync
	fi
fi

if ! [ -e ${CHECKPOINT} ] ; then
   echo Failed to initialize
   exit
fi


######################################################
set -x

NEXT_ITER=`expr ${LAST_STEP}`
date

if [ "$PHASE" = "TRAIN" ]; then
   python -u train_hdc_k_all.py -d "${DATA_TRAIN}" --data_path_base "${DATA_PATH_BASE_TRAIN}"  ${TRAIN_OPT} -e ${NEXT_ITER} 2>&1 | tee -a $LOG_FILE
fi

######################################################

if [ "$PHASE" = "VAL" ]; then
	python -u eval_hdc_k_all.py -s ${SAVE_PATH} ${EMB_OPT} -d "${DATA_TRAIN}" --data_path_base "${DATA_PATH_BASE_TRAIN}"  -o ${EVAL_TRAIN} -b 32 2>&1 | tee -a $LOG_FILE
#	python -u eval_hdc_k_all.py -s ${SAVE_PATH} ${EMB_OPT} -d "${DATA_VAL}" --data_path_base "${DATA_PATH_BASE_TRAIN}"  -o ${EVAL_TEST} -b 32 2>&1 | tee -a $LOG_FILE
fi

######################################################

if [ "$PHASE" = "EVAL" ]; then
       python -u eval_hdc_k_all.py -s ${SAVE_PATH} ${EMB_OPT} -d "${DATA_TEST}" --data_path_base "${DATA_PATH_BASE_TEST}"  -o ${EVAL_TEST} --iter 20000 -b 32 2>&1 | tee -a $LOG_FILE
fi

######################################################

if [ "$PHASE" = "WILDEVAL" ]; then
       python -u eval_hdc_k_all.py -s ${SAVE_PATH} ${EMB_OPT} -d "${DATA_TEST}" --data_path_base "${DATA_PATH_BASE_TEST}"  -o ${EVAL_TEST} --iter 20000 --wild ${BBOX_PATH} -b 32 2>&1 | tee -a $LOG_FILE
fi

